-- EXISTING DOMAIN AUDIT:
-- customers/accounts/transactions/portfolio_holdings/loans are defined in create_schema.py.
-- Iran/oil shock window: 2026-02-01 to 2026-03-10 in data_generator.py; affects market prices,
-- transaction mix/status, and loan delinquency probabilities.
-- Daily update appends transactions and updates account balances/holdings/loan rates; does not
-- mutate customer master data after initial load.
-- Existing domain has no explicit random seed initialization.

CREATE SCHEMA IF NOT EXISTS SE_DEMOS_NEW.WEALTH_POC;

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.DIM_ASSET (
  ASSET_KEY INT NOT NULL PRIMARY KEY,
  ASSET_ID VARCHAR(20) NOT NULL,
  TICKER VARCHAR(10),
  ASSET_NAME VARCHAR(200) NOT NULL,
  ASSET_CLASS VARCHAR(50) NOT NULL,
  SUB_ASSET_CLASS VARCHAR(80),
  SECTOR VARCHAR(80),
  GEOGRAPHY VARCHAR(80),
  CURRENCY VARCHAR(10) DEFAULT 'USD',
  IS_FUND BOOLEAN DEFAULT FALSE,
  FUND_TYPE VARCHAR(50),
  EXPENSE_RATIO DECIMAL(6,4),
  BENCHMARK_INDEX VARCHAR(100),
  ESG_RATING VARCHAR(10),
  ESG_CONTROVERSY_FLAG BOOLEAN DEFAULT FALSE,
  ESG_CONTROVERSY_REASON VARCHAR(200),
  IS_RESTRICTED BOOLEAN DEFAULT FALSE,
  AVERAGE_DAILY_VOLUME BIGINT,
  INCEPTION_DATE DATE,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.DIM_BENCHMARK (
  BENCHMARK_KEY INT NOT NULL PRIMARY KEY,
  BENCHMARK_ID VARCHAR(20) NOT NULL,
  BENCHMARK_NAME VARCHAR(100) NOT NULL,
  BENCHMARK_SHORT_NAME VARCHAR(30) NOT NULL,
  ASSET_CLASS VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(500),
  IS_BLENDED BOOLEAN DEFAULT FALSE,
  BLEND_EQUITY_PCT DECIMAL(5,4),
  BLEND_FIXED_PCT DECIMAL(5,4),
  IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.DIM_INVESTMENT_POLICY (
  POLICY_KEY INT NOT NULL PRIMARY KEY,
  POLICY_ID VARCHAR(20) NOT NULL,
  CUSTOMER_KEY INT NOT NULL,
  RISK_PROFILE VARCHAR(30) NOT NULL,
  TARGET_EQUITY_PCT DECIMAL(5,4) NOT NULL,
  TARGET_FIXED_INCOME_PCT DECIMAL(5,4) NOT NULL,
  TARGET_ALTERNATIVE_PCT DECIMAL(5,4) DEFAULT 0,
  TARGET_CASH_PCT DECIMAL(5,4) DEFAULT 0,
  MAX_SINGLE_POSITION_PCT DECIMAL(5,4) DEFAULT 0.10,
  REBALANCING_DRIFT_THRESHOLD DECIMAL(5,4) NOT NULL,
  REBALANCING_FREQUENCY VARCHAR(20) NOT NULL,
  BENCHMARK_KEY INT NOT NULL,
  HAS_ESG_MANDATE BOOLEAN DEFAULT FALSE,
  ESG_SCREEN_LEVEL VARCHAR(20),
  ESG_EXCLUSION_CATEGORIES VARCHAR(500),
  HAS_RESTRICTED_SECURITIES BOOLEAN DEFAULT FALSE,
  RESTRICTED_TICKERS VARCHAR(500),
  TAX_SENSITIVE BOOLEAN DEFAULT FALSE,
  MIN_LIQUIDITY_DAYS INT DEFAULT 5,
  INCEPTION_DATE DATE NOT NULL,
  LAST_REVIEWED_DATE DATE,
  NEXT_REVIEW_DATE DATE,
  ADVISOR_KEY INT,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.DIM_ADVISOR (
  ADVISOR_KEY INT NOT NULL PRIMARY KEY,
  ADVISOR_ID VARCHAR(20) NOT NULL,
  ADVISOR_NAME VARCHAR(100) NOT NULL,
  TITLE VARCHAR(80),
  TEAM VARCHAR(80),
  AUM_MANAGED DECIMAL(15,2),
  CLIENT_COUNT INT,
  YEARS_AT_FIRM INT,
  CERTIFICATION VARCHAR(200),
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  BACKUP_ADVISOR_KEY INT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE (
  PERFORMANCE_KEY INT NOT NULL PRIMARY KEY,
  CUSTOMER_KEY INT NOT NULL,
  ACCOUNT_KEY INT NOT NULL,
  ADVISOR_KEY INT NOT NULL,
  BENCHMARK_KEY INT NOT NULL,
  PERFORMANCE_DATE DATE NOT NULL,
  BEGINNING_MARKET_VALUE DECIMAL(15,2) NOT NULL,
  ENDING_MARKET_VALUE DECIMAL(15,2) NOT NULL,
  NET_CASH_FLOW DECIMAL(15,2) DEFAULT 0,
  DAILY_RETURN DECIMAL(10,6) NOT NULL,
  MTD_RETURN DECIMAL(10,6) NOT NULL,
  QTD_RETURN DECIMAL(10,6) NOT NULL,
  YTD_RETURN DECIMAL(10,6) NOT NULL,
  ITD_RETURN DECIMAL(10,6) NOT NULL,
  BENCHMARK_DAILY_RETURN DECIMAL(10,6) NOT NULL,
  BENCHMARK_MTD_RETURN DECIMAL(10,6) NOT NULL,
  BENCHMARK_QTD_RETURN DECIMAL(10,6) NOT NULL,
  BENCHMARK_YTD_RETURN DECIMAL(10,6) NOT NULL,
  ACTIVE_RETURN_DAILY DECIMAL(10,6),
  ACTIVE_RETURN_YTD DECIMAL(10,6),
  EQUITY_PCT DECIMAL(6,4),
  FIXED_INCOME_PCT DECIMAL(6,4),
  ALTERNATIVE_PCT DECIMAL(6,4),
  CASH_PCT DECIMAL(6,4),
  EQUITY_DRIFT DECIMAL(6,4),
  MAX_DRIFT DECIMAL(6,4),
  IS_DRIFT_BREACH BOOLEAN,
  DAYS_SINCE_REBALANCE INT,
  TOTAL_COST_BASIS DECIMAL(15,2),
  UNREALIZED_GAIN_LOSS DECIMAL(15,2),
  UNREALIZED_GAIN_LOSS_PCT DECIMAL(10,6),
  MANAGEMENT_FEE_ACCRUAL DECIMAL(12,2),
  FUND_EXPENSE_ACCRUAL DECIMAL(12,2),
  GROSS_RETURN DECIMAL(10,6),
  NET_RETURN DECIMAL(10,6),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS (
  HOLDING_KEY INT NOT NULL PRIMARY KEY,
  CUSTOMER_KEY INT NOT NULL,
  ACCOUNT_KEY INT NOT NULL,
  ASSET_KEY INT NOT NULL,
  SNAPSHOT_DATE DATE NOT NULL,
  QUANTITY DECIMAL(15,4) NOT NULL,
  MARKET_PRICE DECIMAL(12,4) NOT NULL,
  MARKET_VALUE DECIMAL(15,2) NOT NULL,
  COST_BASIS_TOTAL DECIMAL(15,2) NOT NULL,
  COST_BASIS_PER_SHARE DECIMAL(12,4),
  UNREALIZED_GAIN_LOSS DECIMAL(15,2),
  UNREALIZED_GAIN_LOSS_PCT DECIMAL(8,4),
  PORTFOLIO_WEIGHT DECIMAL(6,4),
  ASSET_CLASS_WEIGHT DECIMAL(6,4),
  FIRST_PURCHASE_DATE DATE,
  HOLDING_DAYS INT,
  IS_SHORT_TERM BOOLEAN,
  IS_LOSS_POSITION BOOLEAN,
  IS_TLH_ELIGIBLE BOOLEAN,
  TLH_HARVEST_VALUE DECIMAL(12,2),
  POSITION_ESG_RATING VARCHAR(10),
  VIOLATES_CLIENT_ESG BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.FACT_TRADES (
  TRADE_KEY INT NOT NULL PRIMARY KEY,
  TRADE_ID VARCHAR(30) NOT NULL,
  CUSTOMER_KEY INT NOT NULL,
  ACCOUNT_KEY INT NOT NULL,
  ASSET_KEY INT NOT NULL,
  ADVISOR_KEY INT NOT NULL,
  TRADE_DATE DATE NOT NULL,
  SETTLEMENT_DATE DATE NOT NULL,
  DIRECTION VARCHAR(10) NOT NULL,
  QUANTITY DECIMAL(15,4) NOT NULL,
  EXECUTION_PRICE DECIMAL(12,4) NOT NULL,
  GROSS_AMOUNT DECIMAL(15,2) NOT NULL,
  COMMISSION DECIMAL(10,2) DEFAULT 0,
  NET_AMOUNT DECIMAL(15,2) NOT NULL,
  TRADE_TYPE VARCHAR(30),
  IS_ADVISOR_INITIATED BOOLEAN,
  IS_DISCRETIONARY BOOLEAN,
  BROKER VARCHAR(50),
  ORDER_TYPE VARCHAR(20),
  REALIZED_GAIN_LOSS DECIMAL(12,2),
  IS_WASH_SALE BOOLEAN DEFAULT FALSE,
  NOTES VARCHAR(500),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.FACT_BENCHMARK_RETURNS (
  BENCHMARK_RETURN_KEY INT NOT NULL PRIMARY KEY,
  BENCHMARK_KEY INT NOT NULL,
  RETURN_DATE DATE NOT NULL,
  DAILY_RETURN DECIMAL(10,6) NOT NULL,
  MTD_RETURN DECIMAL(10,6) NOT NULL,
  QTD_RETURN DECIMAL(10,6) NOT NULL,
  YTD_RETURN DECIMAL(10,6) NOT NULL,
  INDEX_LEVEL DECIMAL(12,4),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UNIQUE (BENCHMARK_KEY, RETURN_DATE)
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.FACT_CLIENT_ACTIVITY (
  ACTIVITY_KEY INT NOT NULL PRIMARY KEY,
  CUSTOMER_KEY INT NOT NULL,
  ADVISOR_KEY INT NOT NULL,
  ACTIVITY_DATE DATE NOT NULL,
  ACTIVITY_TYPE VARCHAR(50) NOT NULL,
  CHANNEL VARCHAR(30),
  DURATION_MINUTES INT,
  TOPICS_DISCUSSED VARCHAR(500),
  ACTION_ITEMS VARCHAR(500),
  NEXT_SCHEDULED_DATE DATE,
  SATISFACTION_SCORE INT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.FACT_CASH_FLOWS (
  CASH_FLOW_KEY INT NOT NULL PRIMARY KEY,
  CUSTOMER_KEY INT NOT NULL,
  ACCOUNT_KEY INT NOT NULL,
  FLOW_DATE DATE NOT NULL,
  FLOW_TYPE VARCHAR(30) NOT NULL,
  AMOUNT DECIMAL(15,2) NOT NULL,
  ASSET_KEY INT,
  IS_RECURRING BOOLEAN DEFAULT FALSE,
  RECURRING_FREQUENCY VARCHAR(20),
  NOTES VARCHAR(300),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SE_DEMOS_NEW.WEALTH_POC.ANOMALY_ALERTS (
  ALERT_KEY INT NOT NULL PRIMARY KEY,
  ALERT_DATE DATE NOT NULL,
  ALERT_TYPE VARCHAR(100) NOT NULL,
  SEVERITY VARCHAR(20) NOT NULL,
  CUSTOMER_KEY INT,
  ACCOUNT_KEY INT,
  ADVISOR_KEY INT,
  ALERT_DESCRIPTION VARCHAR(1000),
  RECOMMENDED_ACTION VARCHAR(1000),
  IS_RESOLVED BOOLEAN DEFAULT FALSE,
  RESOLUTION_DATE DATE,
  DOLLAR_IMPACT DECIMAL(15,2),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
