-- EXISTING DOMAIN AUDIT:
-- Existing financial domain tables are in create_schema.py with daily update logic in daily_financial_update.py.
-- Iran/oil anomaly is date-window driven and impacts performance/market behavior in 2026-02-01..2026-03-10.
-- This file adds WEALTH_POC views only and does not alter existing domain objects.

CREATE OR REPLACE VIEW SE_DEMOS_NEW.WEALTH_POC.V_PORTFOLIO_SUMMARY AS
WITH latest_perf AS (
  SELECT *
  FROM SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_KEY, ACCOUNT_KEY ORDER BY PERFORMANCE_DATE DESC) = 1
),
latest_hold AS (
  SELECT CUSTOMER_KEY, ACCOUNT_KEY, MAX(SNAPSHOT_DATE) AS SNAPSHOT_DATE
  FROM SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS
  GROUP BY CUSTOMER_KEY, ACCOUNT_KEY
),
esg_viol AS (
  SELECT h.CUSTOMER_KEY, h.ACCOUNT_KEY, MAX(IFF(h.VIOLATES_CLIENT_ESG, 1, 0)) AS ESG_VIOLATES
  FROM SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS h
  JOIN latest_hold lh ON lh.CUSTOMER_KEY = h.CUSTOMER_KEY AND lh.ACCOUNT_KEY = h.ACCOUNT_KEY AND lh.SNAPSHOT_DATE = h.SNAPSHOT_DATE
  GROUP BY h.CUSTOMER_KEY, h.ACCOUNT_KEY
),
tlh_opp AS (
  SELECT h.CUSTOMER_KEY, h.ACCOUNT_KEY, SUM(COALESCE(h.TLH_HARVEST_VALUE,0)) AS TLH_VALUE
  FROM SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS h
  JOIN latest_hold lh ON lh.CUSTOMER_KEY = h.CUSTOMER_KEY AND lh.ACCOUNT_KEY = h.ACCOUNT_KEY AND lh.SNAPSHOT_DATE = h.SNAPSHOT_DATE
  WHERE h.IS_TLH_ELIGIBLE = TRUE
  GROUP BY h.CUSTOMER_KEY, h.ACCOUNT_KEY
)
SELECT
  'CLIENT-' || LPAD(TO_VARCHAR(p.CUSTOMER_KEY), 5, '0') AS customer_id,
  'Client ' || LPAD(TO_VARCHAR(p.CUSTOMER_KEY), 5, '0') AS client_name,
  'ACCT-' || LPAD(TO_VARCHAR(p.ACCOUNT_KEY), 6, '0') AS account_number,
  p.PERFORMANCE_DATE,
  p.ENDING_MARKET_VALUE,
  p.YTD_RETURN,
  p.BENCHMARK_YTD_RETURN,
  p.ACTIVE_RETURN_YTD,
  p.MAX_DRIFT,
  p.IS_DRIFT_BREACH,
  p.DAYS_SINCE_REBALANCE,
  COALESCE(e.ESG_VIOLATES, 0) > 0 AS ESG_VIOLATION_FLAG,
  COALESCE(t.TLH_VALUE, 0) AS TLH_OPPORTUNITY_VALUE,
  d.ADVISOR_NAME
FROM latest_perf p
LEFT JOIN esg_viol e ON e.CUSTOMER_KEY = p.CUSTOMER_KEY AND e.ACCOUNT_KEY = p.ACCOUNT_KEY
LEFT JOIN tlh_opp t ON t.CUSTOMER_KEY = p.CUSTOMER_KEY AND t.ACCOUNT_KEY = p.ACCOUNT_KEY
LEFT JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_ADVISOR d ON d.ADVISOR_KEY = p.ADVISOR_KEY;

CREATE OR REPLACE VIEW SE_DEMOS_NEW.WEALTH_POC.V_ADVISOR_SCORECARD AS
WITH perf AS (
  SELECT ADVISOR_KEY,
         SUM(ENDING_MARKET_VALUE) AS AUM,
         AVG(ACTIVE_RETURN_YTD) AS AVG_ACTIVE_RETURN_YTD,
         SUM(IFF(IS_DRIFT_BREACH,1,0)) AS DRIFT_BREACH_COUNT
  FROM SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_KEY, ACCOUNT_KEY ORDER BY PERFORMANCE_DATE DESC) = 1
  GROUP BY ADVISOR_KEY
),
contacts AS (
  SELECT ADVISOR_KEY,
         AVG(DATEDIFF('day', MAX_ACTIVITY_DATE, CURRENT_DATE())) AS AVG_DAYS_SINCE_LAST_CONTACT,
         MAX(DATEDIFF('day', MAX_ACTIVITY_DATE, CURRENT_DATE())) AS WORST_DAYS_SINCE_LAST_CONTACT
  FROM (
    SELECT ADVISOR_KEY, CUSTOMER_KEY, MAX(ACTIVITY_DATE) AS MAX_ACTIVITY_DATE
    FROM SE_DEMOS_NEW.WEALTH_POC.FACT_CLIENT_ACTIVITY
    GROUP BY ADVISOR_KEY, CUSTOMER_KEY
  )
  GROUP BY ADVISOR_KEY
)
SELECT
  a.ADVISOR_ID,
  a.ADVISOR_NAME,
  COALESCE(p.AUM,0) AS AUM,
  a.CLIENT_COUNT,
  COALESCE(p.AVG_ACTIVE_RETURN_YTD,0) AS AVG_ACTIVE_RETURN_YTD,
  COALESCE(p.DRIFT_BREACH_COUNT,0) AS DRIFT_BREACH_COUNT,
  COALESCE(c.AVG_DAYS_SINCE_LAST_CONTACT,0) AS AVG_DAYS_SINCE_LAST_CONTACT,
  COALESCE(c.WORST_DAYS_SINCE_LAST_CONTACT,0) AS WORST_DAYS_SINCE_LAST_CONTACT,
  IFF(a.BACKUP_ADVISOR_KEY IS NULL, TRUE, FALSE) AS BACKUP_COVERAGE_FLAG
FROM SE_DEMOS_NEW.WEALTH_POC.DIM_ADVISOR a
LEFT JOIN perf p ON p.ADVISOR_KEY = a.ADVISOR_KEY
LEFT JOIN contacts c ON c.ADVISOR_KEY = a.ADVISOR_KEY;

CREATE OR REPLACE VIEW SE_DEMOS_NEW.WEALTH_POC.V_DRIFT_VIOLATIONS AS
SELECT
  'CLIENT-' || LPAD(TO_VARCHAR(p.CUSTOMER_KEY), 5, '0') AS customer_id,
  'Client ' || LPAD(TO_VARCHAR(p.CUSTOMER_KEY), 5, '0') AS client_name,
  'ACCT-' || LPAD(TO_VARCHAR(p.ACCOUNT_KEY), 6, '0') AS account_number,
  p.PERFORMANCE_DATE,
  p.EQUITY_PCT,
  ip.TARGET_EQUITY_PCT,
  p.MAX_DRIFT,
  p.DAYS_SINCE_REBALANCE,
  ip.REBALANCING_DRIFT_THRESHOLD AS POLICY_THRESHOLD,
  d.ADVISOR_NAME
FROM SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE p
JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_INVESTMENT_POLICY ip ON ip.CUSTOMER_KEY = p.CUSTOMER_KEY
JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_ADVISOR d ON d.ADVISOR_KEY = p.ADVISOR_KEY
WHERE p.PERFORMANCE_DATE = (SELECT MAX(PERFORMANCE_DATE) FROM SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE)
  AND p.IS_DRIFT_BREACH = TRUE;

CREATE OR REPLACE VIEW SE_DEMOS_NEW.WEALTH_POC.V_TLH_OPPORTUNITIES AS
SELECT
  'CLIENT-' || LPAD(TO_VARCHAR(h.CUSTOMER_KEY), 5, '0') AS customer_id,
  'Client ' || LPAD(TO_VARCHAR(h.CUSTOMER_KEY), 5, '0') AS client_name,
  'ACCT-' || LPAD(TO_VARCHAR(h.ACCOUNT_KEY), 6, '0') AS account_number,
  s.ASSET_NAME AS security_name,
  h.UNREALIZED_GAIN_LOSS,
  h.HOLDING_DAYS,
  h.TLH_HARVEST_VALUE
FROM SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS h
JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_ASSET s ON s.ASSET_KEY = h.ASSET_KEY
WHERE h.SNAPSHOT_DATE = (SELECT MAX(SNAPSHOT_DATE) FROM SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS)
  AND h.IS_TLH_ELIGIBLE = TRUE;

CREATE OR REPLACE VIEW SE_DEMOS_NEW.WEALTH_POC.V_ESG_VIOLATIONS AS
SELECT
  'CLIENT-' || LPAD(TO_VARCHAR(h.CUSTOMER_KEY), 5, '0') AS customer_id,
  'Client ' || LPAD(TO_VARCHAR(h.CUSTOMER_KEY), 5, '0') AS client_name,
  'ACCT-' || LPAD(TO_VARCHAR(h.ACCOUNT_KEY), 6, '0') AS account_number,
  s.ASSET_NAME AS security_name,
  s.ESG_RATING,
  s.ESG_CONTROVERSY_REASON,
  ip.ESG_SCREEN_LEVEL AS client_esg_screen_level,
  d.ADVISOR_NAME
FROM SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS h
JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_ASSET s ON s.ASSET_KEY = h.ASSET_KEY
JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_INVESTMENT_POLICY ip ON ip.CUSTOMER_KEY = h.CUSTOMER_KEY
JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_ADVISOR d ON d.ADVISOR_KEY = ip.ADVISOR_KEY
WHERE h.SNAPSHOT_DATE = (SELECT MAX(SNAPSHOT_DATE) FROM SE_DEMOS_NEW.WEALTH_POC.FACT_HOLDINGS)
  AND h.VIOLATES_CLIENT_ESG = TRUE
  AND ip.HAS_ESG_MANDATE = TRUE;

CREATE OR REPLACE VIEW SE_DEMOS_NEW.WEALTH_POC.V_PERFORMANCE_VS_BENCHMARK AS
SELECT
  d.ADVISOR_NAME,
  a.account_type,
  p.CUSTOMER_KEY,
  p.ACCOUNT_KEY,
  p.YTD_RETURN,
  p.BENCHMARK_YTD_RETURN,
  p.ACTIVE_RETURN_YTD,
  p.GROSS_RETURN,
  p.NET_RETURN
FROM SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE p
JOIN SE_DEMOS_NEW.WEALTH_POC.DIM_ADVISOR d ON d.ADVISOR_KEY = p.ADVISOR_KEY
LEFT JOIN (SELECT DISTINCT ACCOUNT_KEY, 'Taxable' AS account_type FROM SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE) a ON a.ACCOUNT_KEY = p.ACCOUNT_KEY
WHERE p.PERFORMANCE_DATE = (SELECT MAX(PERFORMANCE_DATE) FROM SE_DEMOS_NEW.WEALTH_POC.FACT_PORTFOLIO_PERFORMANCE);
