"""Create HEALTHCARE_POC schema and all tables."""
import os
import sys

_hp = os.path.dirname(os.path.abspath(__file__))
if _hp not in sys.path:
    sys.path.insert(0, _hp)

from snowflake_connection import get_snowflake_connection


DDL_STATEMENTS = [
    "CREATE SCHEMA IF NOT EXISTS HEALTHCARE_POC",
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.DIM_PATIENT (
      PATIENT_KEY INT PRIMARY KEY,
      PATIENT_ID VARCHAR,
      AGE_BAND VARCHAR,
      GENDER VARCHAR,
      ZIP_CODE VARCHAR,
      COUNTY VARCHAR,
      PRIMARY_PAYER VARCHAR,
      SECONDARY_PAYER VARCHAR,
      CHRONIC_CONDITIONS VARCHAR,
      RISK_SCORE DECIMAL(5,2),
      IS_ACTIVE BOOLEAN
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.DIM_PROVIDER (
      PROVIDER_KEY INT PRIMARY KEY,
      PROVIDER_ID VARCHAR,
      PROVIDER_NAME VARCHAR,
      SPECIALTY VARCHAR,
      DEPARTMENT VARCHAR,
      FTE_STATUS VARCHAR,
      YEARS_ON_STAFF INT,
      CREDENTIALING_STATUS VARCHAR,
      AVERAGE_LOS_DAYS DECIMAL(5,2),
      AVERAGE_CMI DECIMAL(5,3)
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.DIM_FACILITY (
      FACILITY_KEY INT PRIMARY KEY,
      FACILITY_ID VARCHAR,
      FACILITY_NAME VARCHAR,
      FACILITY_TYPE VARCHAR,
      LICENSED_BEDS INT,
      STAFFED_BEDS INT,
      FLOOR INT,
      BUILDING VARCHAR
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.DIM_DRG (
      DRG_KEY INT PRIMARY KEY,
      DRG_CODE VARCHAR,
      DRG_DESCRIPTION VARCHAR,
      MDC VARCHAR,
      DRG_WEIGHT DECIMAL(6,4),
      GEOMETRIC_MEAN_LOS DECIMAL(5,2),
      ARITHMETIC_MEAN_LOS DECIMAL(5,2),
      DRG_TYPE VARCHAR,
      IS_HRRP_CONDITION BOOLEAN
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.DIM_PAYER (
      PAYER_KEY INT PRIMARY KEY,
      PAYER_ID VARCHAR,
      PAYER_NAME VARCHAR,
      PAYER_TYPE VARCHAR,
      CONTRACT_ON_FILE BOOLEAN,
      CONTRACT_EFFECTIVE_DATE DATE,
      CONTRACT_EXPIRY_DATE DATE
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.DIM_DIAGNOSIS (
      DIAGNOSIS_KEY INT PRIMARY KEY,
      ICD10_CODE VARCHAR,
      DIAGNOSIS_DESCRIPTION VARCHAR,
      CONDITION_GROUP VARCHAR,
      IS_HAC BOOLEAN,
      IS_CHRONIC BOOLEAN,
      HRRP_CONDITION VARCHAR
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.FACT_ENCOUNTER (
      ENCOUNTER_KEY INT PRIMARY KEY,
      ENCOUNTER_ID VARCHAR,
      PATIENT_KEY INT,
      PROVIDER_KEY INT,
      FACILITY_KEY INT,
      DRG_KEY INT,
      PAYER_KEY INT,
      ADMIT_DATE DATE,
      DISCHARGE_DATE DATE,
      LOS_DAYS INT,
      ADMIT_SOURCE VARCHAR,
      DISCHARGE_DISPOSITION VARCHAR,
      PRINCIPAL_DIAGNOSIS_KEY INT,
      SECONDARY_DIAGNOSIS_1_KEY INT,
      SECONDARY_DIAGNOSIS_2_KEY INT,
      PROCEDURE_CODE VARCHAR,
      IS_READMISSION_30 BOOLEAN,
      IS_READMISSION_90 BOOLEAN,
      INDEX_ENCOUNTER_KEY INT,
      HAI_FLAG VARCHAR,
      CASE_MIX_INDEX DECIMAL(5,3),
      SEVERITY_OF_ILLNESS VARCHAR,
      RISK_OF_MORTALITY VARCHAR,
      CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.FACT_FINANCIALS (
      FINANCIAL_KEY INT PRIMARY KEY,
      ENCOUNTER_KEY INT,
      PAYER_KEY INT,
      DRG_KEY INT,
      TOTAL_CHARGES DECIMAL(12,2),
      TOTAL_COST DECIMAL(12,2),
      CONTRACTUAL_ADJUSTMENT DECIMAL(12,2),
      NET_REVENUE DECIMAL(12,2),
      AMOUNT_COLLECTED DECIMAL(12,2),
      UNDERPAYMENT_AMOUNT DECIMAL(12,2),
      DENIAL_FLAG BOOLEAN,
      DENIAL_REASON VARCHAR,
      DENIAL_DATE DATE,
      APPEAL_STATUS VARCHAR,
      GROSS_MARGIN DECIMAL(12,2),
      MARGIN_PCT DECIMAL(6,4),
      OUTLIER_PAYMENT DECIMAL(10,2),
      FISCAL_YEAR INT,
      FISCAL_QUARTER INT,
      CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.FACT_READMISSION (
      READMISSION_KEY INT PRIMARY KEY,
      READMISSION_ENCOUNTER_KEY INT,
      INDEX_ENCOUNTER_KEY INT,
      PATIENT_KEY INT,
      DAYS_TO_READMISSION INT,
      READMISSION_WINDOW VARCHAR,
      INDEX_DRG_KEY INT,
      READMISSION_DRG_KEY INT,
      SAME_CONDITION BOOLEAN,
      HRRP_APPLICABLE BOOLEAN,
      DISCHARGE_DISPOSITION_INDEX VARCHAR,
      CONTRIBUTING_FACTOR VARCHAR,
      PREVENTED_FLAG BOOLEAN,
      CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.FACT_QUALITY_METRICS (
      QUALITY_KEY INT PRIMARY KEY,
      ENCOUNTER_KEY INT,
      FACILITY_KEY INT,
      METRIC_DATE DATE,
      METRIC_TYPE VARCHAR,
      METRIC_VALUE DECIMAL(8,4),
      BENCHMARK_VALUE DECIMAL(8,4),
      PERFORMANCE_BAND VARCHAR,
      CMS_STAR_CONTRIBUTION BOOLEAN,
      REPORTABLE_EVENT BOOLEAN,
      CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.FACT_STAFFING (
      STAFFING_KEY INT PRIMARY KEY,
      FACILITY_KEY INT,
      STAFFING_DATE DATE,
      SHIFT VARCHAR,
      ROLE VARCHAR,
      SCHEDULED_HOURS DECIMAL(6,2),
      ACTUAL_HOURS DECIMAL(6,2),
      OVERTIME_HOURS DECIMAL(6,2),
      AGENCY_HOURS DECIMAL(6,2),
      CENSUS INT,
      NURSE_TO_PATIENT_RATIO DECIMAL(5,2),
      TARGET_RATIO DECIMAL(5,2),
      RATIO_COMPLIANCE BOOLEAN,
      VACANCY_RATE DECIMAL(5,4),
      CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.FACT_CAPACITY (
      CAPACITY_KEY INT PRIMARY KEY,
      FACILITY_KEY INT,
      SNAPSHOT_DATE DATE,
      CENSUS INT,
      LICENSED_BED_OCCUPANCY DECIMAL(5,4),
      STAFFED_BED_OCCUPANCY DECIMAL(5,4),
      ED_BOARDING_HOURS DECIMAL(8,2),
      AVG_DISCHARGE_HOUR DECIMAL(5,2),
      DISCHARGES INT,
      ADMISSIONS INT,
      TRANSFERS_IN INT,
      TRANSFERS_OUT INT,
      DIVERSION_HOURS DECIMAL(6,2),
      ALOS_ROLLING_30 DECIMAL(5,2),
      CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    )
    """,
    """
    CREATE OR REPLACE TABLE HEALTHCARE_POC.ANOMALY_ALERTS (
      ALERT_KEY INT PRIMARY KEY,
      ALERT_DATE DATE,
      ALERT_TYPE VARCHAR,
      SEVERITY VARCHAR,
      FACILITY_KEY INT,
      PROVIDER_KEY INT,
      PAYER_KEY INT,
      ALERT_DESCRIPTION VARCHAR,
      RECOMMENDED_ACTION VARCHAR,
      IS_RESOLVED BOOLEAN,
      RESOLUTION_DATE DATE,
      DOLLAR_IMPACT DECIMAL(12,2),
      CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    )
    """,
]


def main():
    conn = get_snowflake_connection(schema_override="HEALTHCARE_POC")
    cur = conn.cursor()
    try:
        for ddl in DDL_STATEMENTS:
            cur.execute(ddl)
        print("Created HEALTHCARE_POC schema and tables.")
    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    main()
